const ADMIN_EMAIL = 'admin@demo.com';
const ADMIN_PASSWORD = '123456789';

const OWNER_EMAIL = 'owner-1@demo.com';
const OWNER_PASSWORD = '123456789';
const OWNER_2_EMAIL = 'owner-2@demo.com';
const OWNER_2_PASSWORD = '123456789';

const CUSTOMER_EMAIL = 'customer-1@demo.com';
const CUSTOMER_PASSWORD = '123456789';
const CUSTOMER_2_EMAIL = 'customer-2@demo.com';
const CUSTOMER_2_PASSWORD = '123456789';

export {
  ADMIN_EMAIL,
  ADMIN_PASSWORD,
  CUSTOMER_2_EMAIL,
  CUSTOMER_2_PASSWORD,
  CUSTOMER_EMAIL,
  CUSTOMER_PASSWORD,
  OWNER_2_EMAIL,
  OWNER_2_PASSWORD,
  OWNER_EMAIL,
  OWNER_PASSWORD,
};
